apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams-status-app
spec:
  destination:
    namespace: payeros-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment
    repoURL: >-
      https://SRCPAYEROSBITBUCKET@bitbucket.anthem.com/scm/PAYER/teams-status.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_AUTH_TYPE
          value: approle
        - name: AVP_ROLE_ID
          value: 7770ee62-aa20-ee13-26e9-6ff0450fe002
        - name: AVP_SECRET_ID
          value: <VAULT_SECRET_ID>
        - name: AVP_TYPE
          value: vault
        - name: VAULT_ADDR
          value: https://vault.acr.awsdns.internal.das
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_NAMESPACE
          value: dig-10xplat/
  project: default
