apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: teams-status-pipeline
  namespace: payeros-devops
spec:
  params:
    - name: pullRequestName
      type: string
      description: Passed via TriggerTemplate
      default: "Unknown PR"
    - name: latestCommit
      type: string
      description: Passed via TriggerTemplate
      default: "Unknown Commit"
    - name: deploymentEnvironment
      type: string
      description: Passed via TriggerTemplate
      default: "payeros-dev"
  workspaces:
    - name: shared-workspace

  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: https://SRCPAYEROSBITBUCKET@bitbucket.anthem.com/scm/Payer/teams-status.git
        - name: subdirectory
          value: ""
        - name: revision
          value: "$(params.pullRequestName)"
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      workspaces:
        - name: output
          workspace: shared-workspace
      taskRef:
        kind: ClusterTask
        name: git-clone

    - name: run-yaml-lint
      params:
        - name: args
          value: ["./deployment", "-f", "parsable", "-d", "{extends: relaxed, rules: {trailing-spaces: disable, new-line-at-end-of-file: disable, key-duplicates: disable}}"]
      taskRef:
        name: yaml-lint-task
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      runAfter: [ fetch-repository ]

    - name: sonarqube-scan
      params:
        - name: SONAR_HOST_URL
          value: http://sonarqube-payeros-devops.apps.np1.ent-ocp4-np1-useast1.aws.internal.das
        - name: SONAR_PROJECT_KEY
          value: teams-status
        - name: SONAR_USERNAME
          value: admin
        - name: SONAR_PASSWORD
          value: sonarqube
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      taskRef:
        name: sonarqube-scanner
      runAfter: [ fetch-repository ]

    - name: build-and-push-image
      params:
        - name: BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah
        - name: IMAGE
          value: quay.apps.np2.ent-ocp4-np2-useast1.aws.internal.das/payeros/teams-status:$(params.latestCommit)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: docker
        - name: BUILD_EXTRA_ARGS
          value: >-
            --memory=4g
        - name: DOCKER_BUILD_SECRETS
          value: teams-status-build-secrets
      workspaces:
          - name: source
            workspace: shared-workspace
      taskRef:
        name: buildah-custom
      runAfter: [ sonarqube-scan, run-yaml-lint ]

    - name: tag-docker-image
      params:
        - name: appName
          value: "teams-status"
        - name: fileName
          value: "app.yml"
        - name: imageTag
          value: "$(params.latestCommit)"
        - name: branchName
          value: "$(params.pullRequestName)"
        - name: repoURL
          value: "https://SRCPAYEROSBITBUCKET@bitbucket.anthem.com/scm/Payer/teams-status.git"
      taskRef:
        name: update-image-tag
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      runAfter: [ build-and-push-image ]

    - name: sync-argocd
      params:
        - name: application-name
          value: teams-status-app
        - name: revision
          value: "$(params.pullRequestName)"
        - name: flags
          value: --insecure
      taskRef:
        kind: Task
        name: argocd-sync-and-wait-task
      runAfter: [ tag-docker-image ]
