apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teams-status-pvc
  namespace: payeros-devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
