' Generate .png file with .\plantuml.jar -png .\deployment-diagram.wsd

@startuml deployment-diagram
skinparam monochrome true
skinparam nodeShadowing false
skinparam defaultTextAlignment center
skinparam nodesep 5
skinparam ranksep 130

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml

!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml
!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesIng.puml
!includeurl KubernetesPuml/OSS/KubernetesPvc.puml
!includeurl KubernetesPuml/OSS/KubernetesPv.puml
!includeurl KubernetesPuml/OSS/KubernetesSecret.puml
!includeurl KubernetesPuml/OSS/KubernetesCm.puml


node "Argo CD" as argo
Cluster_Boundary(cluster, "OpenShift Cluster") {
    Namespace_Boundary(ns, "payeros-dev") {
        label #white "         <$KubernetesSecret> teams-status-secrets" as secret
        label #white "         <$KubernetesCm> teams-status-config" as config
        label #white "              <$KubernetesIng> teams-status-route" as route
        label #white "               <$KubernetesSvc> teams-status-service"  as service
        label #white "             <$KubernetesDeploy> teams-status-app" as app
    }
}

argo -[dashed]-* app
argo -[dashed]-* service
argo -[dashed]-* route
argo -[dashed]-* config
argo -[dashed]-* secret

@enduml
